---
abstract: 'find the matched position in a text'
author:
  - 'Dai Okabayashi <bayashi@cpan.org>'
build_requires:
  Test::More: 0.88
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4005, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Text-MatchedPosition
provides:
  Text::MatchedPosition:
    file: lib/Text/MatchedPosition.pm
    version: 0.02
requires:
  Carp: 0
  Class::Accessor::Lite: 0
  perl: 5.008001
  strict: 0
  utf8: 0
  warnings: 0
resources:
  bugtracker: http://github.com/bayashi/Text-MatchedPosition/issues
  license: http://dev.perl.org/licenses/
  repository: http://github.com/bayashi/Text-MatchedPosition
version: 0.02
